// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBryA7G284WnQxNo5_iammCp9GqS3Arg8',
    appId: '1:156012573455:web:b1e98a934847884c95c47a',
    messagingSenderId: '156012573455',
    projectId: 'workersscheduler',
    authDomain: 'workersscheduler.firebaseapp.com',
    storageBucket: 'workersscheduler.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfJrhWk5N0KixA7r0RBfsA4J6c1jVfWqU',
    appId: '1:156012573455:android:2e524add1189f9ab95c47a',
    messagingSenderId: '156012573455',
    projectId: 'workersscheduler',
    storageBucket: 'workersscheduler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP8WQdLHaI8S7eypFj9v-hIWhBiw9L9_I',
    appId: '1:156012573455:ios:f36ecb31b065c36795c47a',
    messagingSenderId: '156012573455',
    projectId: 'workersscheduler',
    storageBucket: 'workersscheduler.appspot.com',
    iosClientId: '156012573455-2spmb8hc434u2vggpl16ut1p3jdt8bdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.workersScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP8WQdLHaI8S7eypFj9v-hIWhBiw9L9_I',
    appId: '1:156012573455:ios:f36ecb31b065c36795c47a',
    messagingSenderId: '156012573455',
    projectId: 'workersscheduler',
    storageBucket: 'workersscheduler.appspot.com',
    iosClientId: '156012573455-2spmb8hc434u2vggpl16ut1p3jdt8bdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.workersScheduler',
  );
}
